name: tailor_talk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - langchain==0.1.0
    - openai==1.3.0
    - python-dotenv==1.0.0
    - google-auth==2.28.0
    - google-auth-oauthlib==1.1.0
    - google-auth-httplib2==0.1.1
    - google-api-python-client==2.108.0
    - httpx==0.26.0
    - dateparser==1.1.8
    - pytz==2024.1
